# Generated by Django 6.0 on 2026-02-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_queue_options_queue_symptoms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='room_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
