# Generated by Django 6.0 on 2026-02-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_queue_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='doctor_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
