# Generated by Django 6.0 on 2026-02-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_queue_doctor_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
