# Generated by Django 6.0 on 2026-02-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_queue_check_in_time_queue_is_checked_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='ai_prescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
