# Generated by Django 6.0 on 2026-02-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ['arrival_time']},
        ),
        migrations.AddField(
            model_name='queue',
            name='symptoms',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='queue',
            name='urgency_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='queue',
            name='token_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
